// Predefined room rental mock data with comprehensive fields to demonstrate UI features instantly.

export const MOCK_ROOMS = [
  {
    id: 'room-1',
    roomName: 'Master Suite with Skyline View',
    propertyName: 'Skyline Residences',
    monthlyRent: 950,
    deposit: 1900,
    advanceRental: 950,
    utilitiesCost: 80,
    internetIncluded: true,
    airCon: true,
    privateBathroom: true,
    parking: true,
    washingMachine: true,
    kitchen: true,
    refrigerator: true,
    wardrobe: true,
    studyTable: true,
    bedSize: 'Queen',
    roomSize: 180,
    fullAddress: 'A-22-05 Skyline Residences, Jalan Maarof, Bangsar, Kuala Lumpur',
    area: 'Bangsar',
    city: 'Kuala Lumpur',
    state: 'WP Kuala Lumpur',
    googleMapsLink: 'https://maps.google.com/?q=Bangsar',
    distanceToWorkplace: 2.5,
    distanceToMrtLrt: 0.4,
    distanceToBusStop: 0.1,
    ownerName: 'Mr. Lim',
    agentName: 'Sarah Tan (IQI Realty)',
    phoneNumber: '+60123456789',
    whatsApp: 'https://wa.me/60123456789',
    email: 'sarah.tan@iqi.com',
    sourceWebsite: 'iProperty',
    listingUrl: 'https://www.iproperty.com.my/example1',
    datePosted: '2026-06-15',
    expiryDate: '2026-09-15',
    images: [
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=80'
    ],
    videoUrl: '',
    floorPlanUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80',
    personalNotes: '### Observations:\n* **Good lighting** during afternoons.\n* Very friendly landlord, willing to waive minor maintenance costs.\n* **Near food court** and MRT (Bangsar station).\n\n### Checklist:\n* [x] Call owner\n* [x] Visit room\n* [ ] Check internet speed\n* [x] Inspect bathroom water pressure\n* [ ] Negotiate deposit payment plan',
    status: 'Shortlisted',
    rating: 5,
    favorite: true,
    topChoice: true,
    bestValue: false,
    tags: ['Near MRT', 'Walking Distance', 'High Floor', 'Corner Unit'],
    dateAdded: '2026-06-16T10:00:00.000Z',
    timeline: [
      { status: 'Interested', date: '2026-06-16T10:00:00.000Z', note: 'Saved listing from iProperty.' },
      { status: 'Contacted', date: '2026-06-18T14:30:00.000Z', note: 'Sent WhatsApp to Sarah Tan. Got details.' },
      { status: 'Viewing Scheduled', date: '2026-06-20T09:00:00.000Z', note: 'Scheduled viewing for Sunday 3:00 PM.' },
      { status: 'Viewed', date: '2026-06-22T15:00:00.000Z', note: 'Visited unit. Excellent condition, very quiet.' },
      { status: 'Shortlisted', date: '2026-06-23T11:00:00.000Z', note: 'Shortlisted. Discussing deposit options.' }
    ]
  },
  {
    id: 'room-2',
    roomName: 'Cozy Studio near Station',
    propertyName: 'Mutiara Suites',
    monthlyRent: 750,
    deposit: 1500,
    advanceRental: 750,
    utilitiesCost: 120,
    internetIncluded: false,
    airCon: true,
    privateBathroom: true,
    parking: false,
    washingMachine: true,
    kitchen: true,
    refrigerator: true,
    wardrobe: true,
    studyTable: false,
    bedSize: 'Queen',
    roomSize: 140,
    fullAddress: 'B-10-12 Mutiara Suites, Cheras, Kuala Lumpur',
    area: 'Cheras',
    city: 'Kuala Lumpur',
    state: 'WP Kuala Lumpur',
    googleMapsLink: 'https://maps.google.com/?q=Cheras',
    distanceToWorkplace: 8.2,
    distanceToMrtLrt: 0.2,
    distanceToBusStop: 0.1,
    ownerName: 'Mr. David Ong',
    agentName: '',
    phoneNumber: '+60198765432',
    whatsApp: 'https://wa.me/60198765432',
    email: 'david.ong@gmail.com',
    sourceWebsite: 'PropertyGuru',
    listingUrl: 'https://www.propertyguru.com.my/example2',
    datePosted: '2026-06-20',
    expiryDate: '2026-08-20',
    images: [
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?auto=format&fit=crop&w=800&q=80'
    ],
    videoUrl: '',
    floorPlanUrl: '',
    personalNotes: '### Notes:\n* Quiet environment, facing residential houses instead of main road.\n* Internet not included, needs separate fiber setup ($80/mo).\n* Fridge is a bit small.\n\n### Checklist:\n* [x] Call owner\n* [x] Visit room\n* [ ] Check cellular network signal strength',
    status: 'Contacted',
    rating: 4,
    favorite: true,
    topChoice: false,
    bestValue: true,
    tags: ['Near MRT', 'Walking Distance', 'Quiet Area', 'No Agent Fee'],
    dateAdded: '2026-06-21T08:15:00.000Z',
    timeline: [
      { status: 'Interested', date: '2026-06-21T08:15:00.000Z', note: 'Added studio to dashboard.' },
      { status: 'Contacted', date: '2026-06-22T10:00:00.000Z', note: 'Called David Ong. Landlord lives downstairs.' }
    ]
  },
  {
    id: 'room-3',
    roomName: 'Budget Single Room',
    propertyName: 'Taman Midah Terrace',
    monthlyRent: 450,
    deposit: 450,
    advanceRental: 450,
    utilitiesCost: 50,
    internetIncluded: true,
    airCon: false,
    privateBathroom: false,
    parking: true,
    washingMachine: true,
    kitchen: true,
    refrigerator: true,
    wardrobe: true,
    studyTable: true,
    bedSize: 'Single',
    roomSize: 90,
    fullAddress: 'No. 34, Jalan Midah 5, Cheras, Kuala Lumpur',
    area: 'Cheras',
    city: 'Kuala Lumpur',
    state: 'WP Kuala Lumpur',
    googleMapsLink: 'https://maps.google.com/?q=Taman+Midah',
    distanceToWorkplace: 10.5,
    distanceToMrtLrt: 1.2,
    distanceToBusStop: 0.3,
    ownerName: 'Mrs. Chong',
    agentName: '',
    phoneNumber: '+60176543210',
    whatsApp: 'https://wa.me/60176543210',
    email: '',
    sourceWebsite: 'Mudah.my',
    listingUrl: 'https://www.mudah.my/example3',
    datePosted: '2026-06-24',
    expiryDate: '2026-07-24',
    images: [
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=800&q=80'
    ],
    videoUrl: '',
    floorPlanUrl: '',
    personalNotes: '### Notes:\n* Very affordable. Deposit is only 1 month.\n* No Air-con, only wall fan. Might get hot in afternoon.\n* Shared bathroom with 2 other tenants.\n* Utilities are fixed at $50.\n\n### Checklist:\n* [x] Contact Mrs. Chong\n* [ ] Check room ventilation',
    status: 'Interested',
    rating: 3,
    favorite: false,
    topChoice: false,
    bestValue: true,
    tags: ['No Agent Fee', 'Pet Friendly', 'Male Only'],
    dateAdded: '2026-06-24T15:20:00.000Z',
    timeline: [
      { status: 'Interested', date: '2026-06-24T15:20:00.000Z', note: 'Saved listing. Extremely budget-friendly.' }
    ]
  },
  {
    id: 'room-4',
    roomName: 'Premium Studio Suite',
    propertyName: 'The Park Residences',
    monthlyRent: 1450,
    deposit: 2900,
    advanceRental: 1450,
    utilitiesCost: 150,
    internetIncluded: true,
    airCon: true,
    privateBathroom: true,
    parking: true,
    washingMachine: true,
    kitchen: true,
    refrigerator: true,
    wardrobe: true,
    studyTable: true,
    bedSize: 'King',
    roomSize: 220,
    fullAddress: 'C-31-01 The Park Residences, Bangsar South, Kuala Lumpur',
    area: 'Bangsar',
    city: 'Kuala Lumpur',
    state: 'WP Kuala Lumpur',
    googleMapsLink: 'https://maps.google.com/?q=Bangsar+South',
    distanceToWorkplace: 0.8,
    distanceToMrtLrt: 0.1,
    distanceToBusStop: 0.05,
    ownerName: 'Alex Wong',
    agentName: 'John Lee (JLL Property)',
    phoneNumber: '+60112233445',
    whatsApp: 'https://wa.me/60112233445',
    email: 'john.lee@jll.com',
    sourceWebsite: 'RentInKL',
    listingUrl: 'https://www.rentinkl.com.my/example4',
    datePosted: '2026-06-28',
    expiryDate: '2026-08-28',
    images: [
      'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=800&q=80'
    ],
    videoUrl: '',
    floorPlanUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80',
    personalNotes: '### Notes:\n* Walking distance to office (0.8km, less than 10 mins walk).\n* High-end luxury property. Great pool and gym facilities.\n* Rent is on the higher side. Utilities are metered.\n\n### Checklist:\n* [x] Message John Lee\n* [x] Schedule Viewing\n* [ ] Check room soundproofing',
    status: 'Viewing Scheduled',
    rating: 5,
    favorite: true,
    topChoice: true,
    bestValue: false,
    tags: ['Near MRT', 'Walking Distance', 'High Floor', 'Quiet Area'],
    dateAdded: '2026-06-29T11:45:00.000Z',
    timeline: [
      { status: 'Interested', date: '2026-06-29T11:45:00.000Z', note: 'Found premium listing next to workplace.' },
      { status: 'Contacted', date: '2026-06-29T13:00:00.000Z', note: 'Sarah connected me with agent John Lee.' },
      { status: 'Viewing Scheduled', date: '2026-06-30T10:00:00.000Z', note: 'Viewing confirmed for Saturday at 11:30 AM.' }
    ]
  }
];

export const MOCK_REMINDERS = [
  {
    id: 'rem-1',
    roomId: 'room-4',
    roomName: 'Premium Studio Suite',
    title: 'Viewing Appointment',
    date: '2026-07-04',
    time: '11:30',
    type: 'viewing',
    notes: 'Meet John Lee at Lobby C. Bring umbrella.',
    completed: false
  },
  {
    id: 'rem-2',
    roomId: 'room-1',
    roomName: 'Master Suite with Skyline View',
    title: 'Call owner regarding deposit details',
    date: '2026-07-02',
    time: '15:00',
    type: 'contact',
    notes: 'Ask Mr. Lim if deposit can be paid in two installments.',
    completed: false
  }
];
